# Generated by Django 5.2.8 on 2025-11-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='alert_days_before',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='item',
            name='alert_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
